module.exports={
    TUTOR_COLLECTION:'tutor',
    CLASS_INFO_COLLECTION:'classinfo',
    STUDENT_COLLECTION:'student',
    ASSIGNMENT_COLLECTION:'assignment',
    NOTE_COLLECTION:'note',
    ANNOUNCEMENT_COLLECTION:'announcement',
    EVENT_COLLECTION:'event',
    ORDER_COLLECTION:'order'
}